### ISSUE TITLE
Backwards compatibility with Mvp.Xml 2.3.0

### ISSUE THREAD

**Issue by flyingpie** [devlooped/Mvp.Xml#41]
## Describe the Bug

Some of the methods provided by Mvp.Xml 2.3.0 have effectively been removed, by changing the casing of these methods.

It's not clear to me if this is by design, as part of the v2 -> v3 major version upgrade. I understand if it is, but I'd like to know whether it was on purpose, and whether you'd be open to merging in backwards-compatible methods.

![image](https://github.com/devlooped/Mvp.Xml/assets/1295673/ed6a08ed-eb39-484c-a548-62a3759c43ac)

## Steps to Reproduce
The following template used to work with 2.3.0, but doesn't with 3.0.0+, due to "dateTime()" being renamed to "DateTime()".

I understand that the preferred method is "date-time()", so I'm asking about your thoughts regarding the backwards compat.

```xsl
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:date="http://exslt.org/dates-and-times">

  <xsl:template match="/">
    <root>
      <xsl:value-of select="date:dateTime()" />
    </root>
  </xsl:template>
</xsl:stylesheet>
```

## Expected Behavior

XSL templates that were made to work with 2.3.0 still work in 3.1.0.

## Exception with Stack Trace

```text
System.Xml.Xsl.XslTransformException: Extension object 'http://exslt.org/dates-and-times' does not contain a matching 'dateTime' method that has 0 parameter(s).
```

## Version Info

3.0.0+

**Comment by kzu** [comment]
Oh, that's been an oversight on my part, for sure. Happy to merge a PR!

**Comment by flyingpie** [comment]
@kzu Yeah, I can totally understand that. My main concern was that it does possibly break previously working stuff (as it does in our case), so at least there could be a note in the release notes or something.

To what degree is backwards-compatibility with Mvp.Xml 2.x a concern for you?

**Comment by kzu** [comment]
Not much, since there isn't much new stuff between 2.x and 3.x other than overall modernization. So I don't think it's a large drawack (iow, you're not missing much) to staying with 2.x 🤔 

I'll add a note to the release notes anyway.

**Comment by kzu** [comment]
Updated release notes: https://github.com/devlooped/Mvp.Xml/releases/tag/v3.1.0
